### ISSUE TITLE
truffle2tm

### ISSUE THREAD

**Issue by paulmillr** [SilverTab/tm2truffle#4]
is it hard to make this shit or nope?

**Comment by rxbynerd** [comment]
nah, took about 10 minutes
- `mkdir ~/tm2truffle`
- `cd ~/tm2truffle`
- `git clone https://github.com/SilverTab/tm2truffle`
- `git clone https://github.com/fileability/self-ml`
- `cd tm2truffle`
- `open tm2truffle.xcodeproj`
- under project settings (click the project icon in sidebar to open), change "Architecture -> Base SDK" from "macosx10.7" to "Latest OS X"
- Cmd-S to save
- `xcodebuild`
- finished binary is at `build/Release/tm2truffle`
